name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.14']
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: |
          go get -u github.com/jteeuwen/go-bindata/...
      - name: Build, test and install
        run: |
          cd ./rimugo
          go-bindata ./resources
          cd ..
          go test ./...
          go install ./...